#! /bin/sh
### BEGIN INIT INFO
# Provides:          HomeAssistantRemoteCEC
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts & Stops HomeAssistantRemoteCEC
# Description:       Starts & Stops HomeAssistantRemoteCEC
### END INIT INFO

case "$1" in
    start)
        bash /Home-Assistant-remote-cec/start.sh &
        ;;

    stop)
        ;;

    restart)
        ;;
	*)
		echo "(start|stop|restart)"
		;;
esac

exit 0
